server:
  host: "127.0.0.2"
  port: 8080
  mode: "cli"

paths:
  coordinator_db:  "./data/coordinator.db"
  forensic_db_dir: "./data/forensic/"
  default_db:      "./data/default.db"
  evidence_db_dir: "./data/evidence/"

hosts_management:
  enabled: false

logging:
  level: "debug"
  logfile: "./logs/forensic_server.log"
